//
//  MNBMainViewController.m
//  MyItems
//
//  Created by Marcelo Busico on 28/07/14.
//  Copyright (c) 2014 Marcelo Busico. All rights reserved.
//

#import "MNBMainViewController.h"
#import "MNBCreateItemMainDataViewController.h"
#import "MBProgressHUD.h"
#import "MNBItemEntity.h"

@interface MNBMainViewController () <MBProgressHUDDelegate> {
    MBProgressHUD *HUD;
}

@end

@implementation MNBMainViewController

- (id)init
{
    self = [super initWithNibName:NSStringFromClass([self class])
                           bundle:[NSBundle mainBundle]];
    if (self) {
        // Custom initialization
        self.title = @"Create Items";
        self.tabBarItem = [[UITabBarItem alloc] initWithTitle:@"Create Items" image:[UIImage imageNamed:@"newIcon"] tag:0];
    }
    
    return self;
}

- (void)viewDidLoad
{
    [super viewDidLoad];
    // Do any additional setup after loading the view from its nib.
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (IBAction)optionCreateNewItem:(id)sender {
    MNBCreateItemMainDataViewController *createItemMainDataViewController = [[MNBCreateItemMainDataViewController alloc] init];
    
    [self.navigationController pushViewController:createItemMainDataViewController
                                         animated:YES];
}

- (IBAction)optionGenerateLotOfItems:(id)sender {
    HUD = [[MBProgressHUD alloc] initWithView:self.navigationController.view];
	[self.navigationController.view addSubview:HUD];
	
	// Set determinate bar mode
	HUD.mode = MBProgressHUDModeDeterminateHorizontalBar;
	
	HUD.delegate = self;
	
    [HUD show:YES];
    
    static int AMOUNT_OF_ITEMS = 20;
    NSUserDefaults *userDefaults = [NSUserDefaults standardUserDefaults];
    NSInteger totalItems = [userDefaults integerForKey:@"totalItems"];
    
    for (int i=1; i <= AMOUNT_OF_ITEMS; i++) {
        NSInteger itemNumber = i + totalItems;
        MNBItemEntity *itemEntity = [[MNBItemEntity alloc] init];
        itemEntity.title = [NSString stringWithFormat:@"Autogenerated #%d", itemNumber];
        itemEntity.subTitle = [NSString stringWithFormat:@"Subtitle #%d", itemNumber];
        itemEntity.price = [NSNumber numberWithFloat:123.45f];
        [itemEntity persistItem];
        HUD.progress = (i / AMOUNT_OF_ITEMS);
    }
    
    [HUD hide:YES];
}

@end
